"""
Atlas Executive Insight Engine

Responsibility: explain KPI movements, not calculate them.

Every insight is generated by comparing a KPIResult's current vs previous
breakdown dimensions and applying threshold-based business rules — there
is no hardcoded narrative text per metric. The headline string is built
from a small set of composable templates parameterised by the actual
computed numbers, so the same code path produces correct sentences for
any KPI/period/magnitude combination.

Pipeline:
    KPIResult (with breakdown dict)
        -> _attribute_drivers()   : which dimension moved the most
        -> _classify_movement()   : opportunity / risk / neutral, confidence
        -> _build_headline()      : template-based sentence construction
        -> Insight
"""

from __future__ import annotations

from datetime import date
from typing import Dict, List, Optional

from loguru import logger

from analytics.core.data_context import DataContext, get_data_context
from analytics.core.types import Insight, KPIResult, Trend
from analytics.kpis.registry import compute, compute_all

# Movement classification thresholds — business-rule driven, not arbitrary.
SIGNIFICANT_MOVE_PCT = 5.0     # below this, a move is "flat" / not worth flagging
LARGE_MOVE_PCT = 15.0          # above this, confidence is "high"
RISK_METRICS = {
    "churn_rate", "fraud_rate", "failed_transaction_rate", "kyc_processing_time",
}
OPPORTUNITY_DIRECTION_UP = {
    "total_revenue", "monthly_active_users", "premium_conversion_rate",
    "retention_rate", "cross_sell_rate", "product_adoption", "arpu", "clv",
    "ltv_cac_ratio", "new_customers", "returning_customers", "csat",
    "kyc_approval_rate", "product_stickiness", "revenue_growth",
}


def _attribute_drivers(result: KPIResult, top_n: int = 3) -> List[str]:
    """
    Identify which dimension(s) within a KPI's breakdown contributed most
    to its absolute value. Returns human-readable "<dimension>=<key>"
    strings ordered by contribution, largest first.

    This is statistical attribution (largest share of the total), not a
    causal claim — the headline language reflects that distinction.
    """
    drivers: List[str] = []
    for dim_name, dim_values in result.breakdown.items():
        if not dim_values:
            continue
        ranked = sorted(dim_values.items(), key=lambda kv: abs(kv[1]), reverse=True)
        for key, val in ranked[:top_n]:
            label = dim_name.replace("by_", "").rstrip("s")
            drivers.append(f"{label}={key} ({val:,.2f})")
    return drivers[:top_n]


def _classify_movement(result: KPIResult) -> tuple[bool, bool, str]:
    """
    Returns (is_opportunity, is_risk, confidence) based on the KPI's name,
    direction, and magnitude. A metric moving "up" is an opportunity only
    if that metric is in OPPORTUNITY_DIRECTION_UP (e.g. churn_rate going
    up is the opposite — handled via RISK_METRICS).
    """
    if result.delta_pct is None:
        return False, False, "low"

    magnitude = abs(result.delta_pct)
    if magnitude < SIGNIFICANT_MOVE_PCT:
        confidence = "low"
    elif magnitude < LARGE_MOVE_PCT:
        confidence = "medium"
    else:
        confidence = "high"

    is_risk_metric = result.name in RISK_METRICS
    went_up = result.trend == Trend.UP

    if is_risk_metric:
        is_risk = went_up
        is_opportunity = (not went_up) and magnitude >= SIGNIFICANT_MOVE_PCT
    elif result.name in OPPORTUNITY_DIRECTION_UP:
        is_opportunity = went_up and magnitude >= SIGNIFICANT_MOVE_PCT
        is_risk = (not went_up) and magnitude >= SIGNIFICANT_MOVE_PCT
    else:
        is_opportunity = False
        is_risk = False

    return is_opportunity, is_risk, confidence


def _build_headline(result: KPIResult, direction_word: str) -> str:
    """
    Compose a headline sentence from the KPI's own data — no per-metric
    hardcoded strings. The template varies only by unit type so numbers
    render correctly (gbp vs percent vs count vs ratio).
    """
    label = result.name.replace("_", " ")
    pct = abs(result.delta_pct or 0.0)

    if result.unit == "gbp":
        value_str = f"£{result.value:,.0f}"
    elif result.unit == "percent":
        value_str = f"{result.value:.1f}%"
    elif result.unit == "ratio":
        value_str = f"{result.value:.2f}"
    else:
        value_str = f"{result.value:,.0f}"

    period = f" in {result.period_label}" if result.period_label else ""
    return f"{label.capitalize()} {direction_word} {pct:.1f}% to {value_str}{period}"


def explain(name: str, ctx: Optional[DataContext] = None,
           as_of: Optional[date] = None) -> Optional[Insight]:
    """
    Generate an Insight for a single KPI by name. Returns None if the
    KPI has no previous_value to compare against (nothing to explain yet)
    or if the movement is below the significance threshold.
    """
    result = compute(name, ctx=ctx, as_of=as_of)
    if result.delta_pct is None:
        return None
    if abs(result.delta_pct) < SIGNIFICANT_MOVE_PCT:
        return None

    is_opportunity, is_risk, confidence = _classify_movement(result)
    direction_word = "increased" if result.trend == Trend.UP else "decreased"
    headline = _build_headline(result, direction_word)
    drivers = _attribute_drivers(result)

    domain_map = {
        "daily_active_users": "customer", "weekly_active_users": "customer",
        "monthly_active_users": "customer", "active_customers": "customer",
        "new_customers": "customer", "returning_customers": "customer",
        "churn_rate": "customer", "retention_rate": "customer",
        "premium_conversion_rate": "customer",
        "total_revenue": "revenue", "revenue_by_product": "revenue",
        "revenue_by_country": "revenue", "revenue_by_segment": "revenue",
        "arpu": "revenue", "clv": "revenue", "ltv_cac_ratio": "revenue",
        "revenue_growth": "revenue",
        "product_adoption": "product", "product_stickiness": "product",
        "cross_sell_rate": "product", "feature_adoption": "product",
        "kyc_approval_rate": "operations", "kyc_processing_time": "operations",
        "support_resolution_time": "operations", "csat": "operations",
        "fraud_rate": "operations", "failed_transaction_rate": "operations",
    }

    return Insight(
        headline=headline,
        category=domain_map.get(name, "general"),
        direction=result.trend or Trend.FLAT,
        magnitude_pct=abs(result.delta_pct),
        primary_driver=drivers[0] if drivers else "no dimensional breakdown available",
        contributing_factors=drivers[1:] if len(drivers) > 1 else [],
        supporting_kpis=[name],
        is_opportunity=is_opportunity,
        is_risk=is_risk,
        confidence=confidence,
        metadata={
            "current_value": result.value, "previous_value": result.previous_value,
            "as_of": result.as_of.isoformat(),
        },
    )


def generate_executive_insights(ctx: Optional[DataContext] = None,
                                as_of: Optional[date] = None,
                                max_insights: int = 10) -> List[Insight]:
    """
    Generate the full set of executive insights across every registered
    KPI. Insights are ranked by magnitude_pct (largest business movement
    first) and capped at max_insights — executives need the handful of
    things that matter, not 27 paragraphs.
    """
    ctx = ctx or get_data_context()
    as_of = as_of or ctx.as_of()

    all_kpis = compute_all(ctx=ctx, as_of=as_of)
    insights: List[Insight] = []

    for name, result in all_kpis.items():
        insight = explain(name, ctx=ctx, as_of=as_of)
        if insight:
            insights.append(insight)

    insights.sort(key=lambda i: i.magnitude_pct, reverse=True)
    logger.info(
        f"[InsightEngine] Generated {len(insights)} insights "
        f"({sum(1 for i in insights if i.is_risk)} risks, "
        f"{sum(1 for i in insights if i.is_opportunity)} opportunities)"
    )
    return insights[:max_insights]


def generate_risk_insights(ctx: Optional[DataContext] = None,
                           as_of: Optional[date] = None) -> List[Insight]:
    """Subset of generate_executive_insights() filtered to is_risk=True."""
    return [i for i in generate_executive_insights(ctx, as_of, max_insights=27) if i.is_risk]


def generate_opportunity_insights(ctx: Optional[DataContext] = None,
                                  as_of: Optional[date] = None) -> List[Insight]:
    """Subset of generate_executive_insights() filtered to is_opportunity=True."""
    return [i for i in generate_executive_insights(ctx, as_of, max_insights=27) if i.is_opportunity]
